version: "3.7"
services:

  # this file only contains a small part of the container definitions
  # please check the compose files in the 'compose' folder
  # you should use the built in bin/ scripts to run commands as it makes your life easier
  # otherwise you need to run something like:
  # docker-compose -f docker-compose.yml -f compose/nginx.yml -f compose/pgsql.yml -f compose/php.yml up -d pgsql php-7.3

  nodejs:
    image: node:16-alpine
    container_name: totara_nodejs
    environment:
      TZ: ${TIME_ZONE}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
    working_dir: ${REMOTE_SRC}

  mailcatcher:
    image: tophfr/mailcatcher
    container_name: totara_mailcatcher
    ports:
      - "8080:80"
    environment:
      TZ: ${TIME_ZONE}
    networks:
      - totara

  redis:
    image: redis:alpine
    # activate persistency
    command: "redis-server --appendonly yes"
    environment:
      TZ: ${TIME_ZONE}
    volumes:
      - redis-data:/data
    networks:
      - totara

  memcached:
    image: memcached:alpine
    environment:
      TZ: ${TIME_ZONE}
    networks:
      - totara

volumes:
  totara-data:
  redis-data:

networks:
  totara:
    name: totara