version: "3"
services:

  nginx:
    build:
      context: nginx
      args:
        - REMOTE_DATA
    ports:
      - "80:80"
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
    networks:
      totara:
        aliases:
            - totara71.behat
            - totara56.behat

  php-5.6:
    build:
      context: php
      dockerfile: Dockerfile-56
      args:
        - XDEBUG_ENABLE=1
        - REMOTE_SRC
        - REMOTE_DATA
    working_dir: ${REMOTE_SRC}
    environment:
      XDEBUG_CONFIG: remote_host=${HOST_IP}
      PHP_IDE_CONFIG: serverName=totara56
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
    networks:
      - totara

  php-5.6-noxdebug:
    build:
      context: php
      dockerfile: Dockerfile-56
      args:
        - XDEBUG_ENABLE=0
        - REMOTE_SRC
        - REMOTE_DATA
    working_dir: ${REMOTE_SRC}
    environment:
      XDEBUG_CONFIG: remote_host=${HOST_IP}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
    networks:
      - totara

  php-7.0:
    build:
      context: php
      dockerfile: Dockerfile-70
      args:
        - XDEBUG_ENABLE=1
        - REMOTE_SRC
        - REMOTE_DATA
    working_dir: ${REMOTE_SRC}
    environment:
      XDEBUG_CONFIG: remote_host=${HOST_IP}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
    networks:
      - totara

  php-7.0-noxdebug:
    build:
      context: php
      dockerfile: Dockerfile-70
      args:
        - XDEBUG_ENABLE=0
        - REMOTE_SRC
        - REMOTE_DATA
    working_dir: ${REMOTE_SRC}
    environment:
      XDEBUG_CONFIG: remote_host=${HOST_IP}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
    networks:
      - totara

  php-7.1:
    build:
      context: php
      dockerfile: Dockerfile-71
      args:
        - XDEBUG_ENABLE=1
        - REMOTE_SRC
        - REMOTE_DATA
    working_dir: ${REMOTE_SRC}
    environment:
      XDEBUG_CONFIG: remote_host=${HOST_IP}
      PHP_IDE_CONFIG: serverName=totara71
      HIST_FILE: /root/.bash_history
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ~/.bash_history:/root/.bash_history
    networks:
      - totara

  php-7.1-noxdebug:
    build:
      context: php
      dockerfile: Dockerfile-71
      args:
        - XDEBUG_ENABLE=0
    working_dir: ${REMOTE_SRC}
    environment:
      HIST_FILE: /root/.bash_history
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ~/.bash_history:/root/.bash_history
    networks:
      - totara

  php-7.2:
    build:
      context: php
      dockerfile: Dockerfile-72
    working_dir: ${REMOTE_SRC}
    environment:
      XDEBUG_CONFIG: remote_host=${HOST_IP}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
    networks:
      - totara

  nodejs:
    image: node:4.8.7
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
    working_dir: ${REMOTE_SRC}

  pgsql:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    networks:
      - totara

  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - totara

  mssql:
    image: microsoft/mssql-server-linux
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${MSSQL_SA_PW}
      MSSQL_PID: Developer
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - totara

  selenium-hub:
    image: selenium/hub:3.7.1
    ports:
      - "4444:4444"
    networks:
      - totara
    environment:
      - GRID_MAX_SESSION=8
      - GRID_TIMEOUT=7200
      - GRID_CLEAN_UP_CYCLE=120000

  selenium-chrome:
    image: selenium/node-chrome:3.7.1
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_INSTANCES=8
      - NODE_MAX_SESSION=8
    networks:
      - totara

  selenium-chrome-standalone:
    image: selenium/standalone-chrome:3.7.1
    networks:
      - totara

  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - "8080:80"
    networks:
      - totara

volumes:
    pgsql-data:
    mssql-data:
    mysql-data:
    totara-data:

networks:
  totara:
