version: "2"
services:

  nginx:
    image: totara/docker-dev-nginx
    container_name: totara_nginx
    environment:
        - REMOTE_DATA
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
    depends_on:
      - mailcatcher
    networks:
      totara:
        aliases:
            - totara54
            - totara54.behat
            - totara54.behat.totaralms.com
            - totara55
            - totara55.behat
            - totara55.behat.totaralms.com
            - totara56
            - totara56.behat
            - totara56.behat.totaralms.com
            - totara70
            - totara70.behat
            - totara70.behat.totaralms.com
            - totara71
            - totara71.behat
            - totara71.behat.totaralms.com
            - totara72
            - totara72.behat
            - totara72.behat.totaralms.com
            - totara73
            - totara73.behat
            - totara73.behat.totaralms.com

  php-5.4:
    image: totara/docker-dev-php54
    container_name: totara_php54
    working_dir: ${REMOTE_SRC}
    environment:
      HIST_FILE: /root/.bash_history
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
    depends_on:
      - php-5.4-debug
    networks:
      - totara

  php-5.4-debug:
    image: totara/docker-dev-php54-debug
    container_name: totara_php54_debug
    working_dir: ${REMOTE_SRC}
    environment:
      HOST_IP: ${HOST_IP}
      PHP_IDE_CONFIG: serverName=totara54
      HIST_FILE: /root/.bash_history
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
    networks:
      - totara

  php-5.4-cron:
    image: totara/docker-dev-php54-cron
    container_name: totara_php54_cron
    volumes:
    - ${LOCAL_SRC}:${REMOTE_SRC}
    - totara-data:${REMOTE_DATA}
    - ./cron.d:/etc/cron.d
    networks:
    - totara

  php-5.5:
    image: totara/docker-dev-php55
    container_name: totara_php55
    working_dir: ${REMOTE_SRC}
    environment:
      HIST_FILE: /root/.bash_history
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
    depends_on:
      - php-5.5-debug
    networks:
      - totara

  php-5.5-debug:
    image: totara/docker-dev-php55-debug
    container_name: totara_php55_debug
    working_dir: ${REMOTE_SRC}
    environment:
      XDEBUG_CONFIG: remote_host=${HOST_IP}
      PHP_IDE_CONFIG: serverName=totara55
      HIST_FILE: /root/.bash_history
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
    networks:
      - totara

  php-5.5-cron:
    image: totara/docker-dev-php55-cron
    container_name: totara_php55_cron
    volumes:
    - ${LOCAL_SRC}:${REMOTE_SRC}
    - totara-data:${REMOTE_DATA}
    - ./cron.d:/etc/cron.d
    networks:
    - totara

  php-5.6:
    image: totara/docker-dev-php56
    container_name: totara_php56
    working_dir: ${REMOTE_SRC}
    environment:
      HIST_FILE: /root/.bash_history
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
    depends_on:
      - php-5.6-debug
    networks:
      - totara

  php-5.6-debug:
    image: totara/docker-dev-php56-debug
    container_name: totara_php56_debug
    working_dir: ${REMOTE_SRC}
    environment:
      XDEBUG_CONFIG: remote_host=${HOST_IP}
      PHP_IDE_CONFIG: serverName=totara56
      HIST_FILE: /root/.bash_history
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
    networks:
      - totara

  php-5.6-cron:
    image: totara/docker-dev-php56-cron
    container_name: totara_php56_cron
    volumes:
    - ${LOCAL_SRC}:${REMOTE_SRC}
    - totara-data:${REMOTE_DATA}
    - ./cron.d:/etc/cron.d
    networks:
    - totara

  php-7.0:
    image: totara/docker-dev-php70
    container_name: totara_php70
    working_dir: ${REMOTE_SRC}
    environment:
      HIST_FILE: /root/.bash_history
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
    depends_on:
      - php-7.0-debug
    networks:
      - totara

  php-7.0-debug:
    image: totara/docker-dev-php70-debug
    container_name: totara_php70_debug
    working_dir: ${REMOTE_SRC}
    environment:
      XDEBUG_CONFIG: remote_host=${HOST_IP}
      PHP_IDE_CONFIG: serverName=totara70
      HIST_FILE: /root/.bash_history
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
    networks:
      - totara

  php-7.0-cron:
    image: totara/docker-dev-php70-cron
    container_name: totara_php70_cron
    volumes:
    - ${LOCAL_SRC}:${REMOTE_SRC}
    - totara-data:${REMOTE_DATA}
    - ./cron.d:/etc/cron.d
    networks:
    - totara

  php-7.1:
    image: totara/docker-dev-php71
    container_name: totara_php71
    working_dir: ${REMOTE_SRC}
    environment:
      HIST_FILE: /root/.bash_history
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
    depends_on:
      - php-7.1-debug
    networks:
      - totara

  php-7.1-debug:
    image: totara/docker-dev-php71-debug
    container_name: totara_php71_debug
    working_dir: ${REMOTE_SRC}
    environment:
      XDEBUG_CONFIG: remote_host=${HOST_IP}
      PHP_IDE_CONFIG: serverName=totara71
      HIST_FILE: /root/.bash_history
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
    networks:
      - totara

  php-7.1-cron:
    image: totara/docker-dev-php71-cron
    container_name: totara_php71_cron
    volumes:
    - ${LOCAL_SRC}:${REMOTE_SRC}
    - totara-data:${REMOTE_DATA}
    - ./cron.d:/etc/cron.d
    networks:
    - totara

  php-7.2:
    image: totara/docker-dev-php72
    container_name: totara_php72
    working_dir: ${REMOTE_SRC}
    environment:
      HIST_FILE: /root/.bash_history
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
    depends_on:
      - php-7.2-debug
    networks:
      - totara

  php-7.2-debug:
    image: totara/docker-dev-php72-debug
    container_name: totara_php72_debug
    working_dir: ${REMOTE_SRC}
    environment:
      XDEBUG_CONFIG: remote_host=${HOST_IP}
      PHP_IDE_CONFIG: serverName=totara72
      HIST_FILE: /root/.bash_history
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
    networks:
      - totara

  php-7.2-cron:
    image: totara/docker-dev-php72-cron
    container_name: totara_php72_cron
    volumes:
    - ${LOCAL_SRC}:${REMOTE_SRC}
    - totara-data:${REMOTE_DATA}
    - ./cron.d:/etc/cron.d
    networks:
    - totara

  php-7.3:
    image: totara/docker-dev-php73
    container_name: totara_php73
    working_dir: ${REMOTE_SRC}
    environment:
      HIST_FILE: /root/.bash_history
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
    depends_on:
      - php-7.3-debug
    networks:
      - totara

  php-7.3-debug:
    image: totara/docker-dev-php73-debug
    container_name: totara_php73_debug
    working_dir: ${REMOTE_SRC}
    environment:
      XDEBUG_CONFIG: remote_host=${HOST_IP}
      PHP_IDE_CONFIG: serverName=totara73
      HIST_FILE: /root/.bash_history
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
    networks:
      - totara

  php-7.3-cron:
    image: totara/docker-dev-php73-cron
    container_name: totara_php73_cron
    volumes:
    - ${LOCAL_SRC}:${REMOTE_SRC}
    - totara-data:${REMOTE_DATA}
    - ./cron.d:/etc/cron.d
    networks:
    - totara

  nodejs:
    image: node:8.11
    container_name: totara_nodejs
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
    working_dir: ${REMOTE_SRC}

  pgsql:
    image: postgres:11.1
    container_name: totara_pgsql
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    depends_on:
     - nginx
    networks:
      - totara

  pgsql10:
    image: postgres:10.6
    container_name: totara_pgsql
    ports:
      - "5410:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgsql10-data:/var/lib/postgresql/data
    depends_on:
     - nginx
    networks:
      - totara

  pgsql93:
    image: postgres:9.3
    container_name: totara_pgsql93
    ports:
      - "5493:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgsql93-data:/var/lib/postgresql/data
    depends_on:
     - nginx
    networks:
      - totara

  mysql8:
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
    depends_on:
      - nginx
    volumes:
      - mysql80-data:/var/lib/mysql
      - ./mysql8:/etc/mysql/conf.d
    networks:
      - totara

  mysql:
    image: mysql:5.7
    container_name: totara_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
    depends_on:
      - nginx
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - totara

  mariadb:
    image: mariadb:10
    container_name: totara_mariadb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./mariadb:/etc/mysql/conf.d
    depends_on:
      - nginx
    mem_swappiness: 1
    networks:
      - totara

  mssql:
    image: totara/docker-dev-mssql
    container_name: totara_mssql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${MSSQL_SA_PW}
      MSSQL_PID: Developer
    volumes:
      - mssql-data:/var/opt/mssql
    depends_on:
      - nginx
    networks:
      - totara

  selenium-hub:
    image: selenium/hub:3.13
    container_name: totara_seleniumhub
    ports:
      - "4444:4444"
    networks:
      - totara
    environment:
      - GRID_MAX_SESSION=8
      - GRID_TIMEOUT=7200
      - GRID_CLEAN_UP_CYCLE=120000
    depends_on:
      - selenium-chrome

  selenium-chrome:
    image: selenium/node-chrome:3.13
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_INSTANCES=8
      - NODE_MAX_SESSION=8
    networks:
      - totara

  selenium-chrome-debug:
    image: selenium/standalone-chrome-debug:3.13
    container_name: totara_chrome_standalone_debug
    ports:
      - "5900:5900"
    networks:
      - totara

  selenium-chrome-standalone:
    image: selenium/standalone-chrome:3.13
    container_name: totara_chrome_standalone
    ports:
      - "4445:4444"
    networks:
      - totara

  mailcatcher:
    image: tophfr/mailcatcher
    container_name: totara_mailcatcher
    ports:
      - "8080:80"
    networks:
      - totara

  redis:
    image: redis
    # activate persistency
    command: "redis-server --appendonly yes"
    volumes:
      - redis-data:/data
    networks:
      - totara

volumes:
    pgsql-data:
    pgsql10-data:
    pgsql93-data:
    mssql-data:
    mysql-data:
    mysql80-data:
    totara-data:
    mariadb-data:
    redis-data:

networks:
  totara:
