name: Build MSSQL images

on:
  release:
    types:
      - created
  pull_request:
    branches:
      - master
    paths:
      - mssql/**
      - ./.github/workflows/build-image.yml

jobs:
  build-mssql-images:
    name: Build MSSQL images
    strategy:
      fail-fast: false
      matrix:
        version: [2017, 2019, 2022]
    uses: ./.github/workflows/build-image.yml
    with:
      image: mssql${{ matrix.version }}
      context: ./mssql
      dockerfile: ${{ matrix.version }}/Dockerfile
      multiarch: false # Mssql does not support multiple architectures
      push: ${{ github.event_name == 'release' }}
    secrets: inherit
